import React, { useEffect, useState } from 'react'
import './report.scss'
import { Link, useParams } from 'react-router-dom'
import { latestData } from '../../data/latestData';
import { Tab, Tabs } from 'react-bootstrap';

const Report = () => {
  const [tabKey, initTabKey] = useState('desc')
  const[report,setReport]=useState([])
  let {id} = useParams();
  useEffect(()=>{
    const findSingleReport = latestData.find((item)=>item.id==id)
    setReport(findSingleReport)
  },[id])
  return (
    <div className='content-wrapper'>
        <div className='container-fluid'>
          <div className='report-banner'>
          <div className='row'>
              <div className='col-lg-9'>
                  <div className='card border-0'>
                      <div className='card-body'>
                        <h5 className='title'>{report.title}</h5>
                        <p className='desc'>{report.desc}</p>
                      </div>
                  </div>
              </div>
              <div className='col-lg-3'>
                <div className='btn-list'>
                  <button className='btn btn-success sampleBtn'>Download Sample</button>
                  <button className='btn btn-primary talkBtn'>Talk to Analyst</button>
                </div>
              </div>
          </div>
          </div>
          <div className='content-main'>
            <div className='row'>
              <div className='col-lg-9'>
              <main className='tabContent'>
                <Tabs activeKey={tabKey} onSelect={(e) => initTabKey(e)} className='custom-tabs'>
                  <Tab eventKey="desc" title="Description">
                    <h5>The global inverter market size </h5>
                    <p>
                    Inverters, which are a fundamental component of solar or wind power systems, function by converting DC to AC electrical energy. In terms of solar energy, inverters play an important role in converting DC power generated by solar panels into usable electricity to be used for homes, businesses and the grid. This will allow efficient use of the sun's power and reduce dependency on traditional sources of energy, thereby helping to minimize carbon emissions.
                    </p>
                    <p>In the wind power sector, furthermore, converters to convert electricity from DC sources generated by wind turbines for use as an active electrical current are widely applied. As a result, the homes and businesses get their electricity from this AC power. The use of inverters will allow wind <Link to=''> power installations to achieve</Link> efficient conversion of the energies generated from wind turbines for usable electricity, in order to promote environmentally sound energy practices.</p>
                    <p>The main drivers to the growth of the global Inverter market are an increasing number of installs of solar power systems and growing demand for energy-efficient solutions in industrial automation. Find out what an inverter is doing to convert DC power into AC and promote energy efficiency.</p>
                    <h5>Growth Factors:</h5>
                    <p>The global inverter market is experiencing significant growth, driven by several factors. One of the major factors is the increasing adoption of solar power systems across various regions. As concerns regarding climate change and the need to reduce carbon emissions continue to grow, the focus on renewable energy sources, particularly solar energy, has also increased. Inverters, which convert DC energy generated by solar arrays into usable AC power for households, businesses and electricity grids, play a crucial role in the Solar Power System.</p>
                    <p>The industrial automation sector is also a key area in which the market for inverters will continue to grow. As a result of the <Link to=''>demand for more energy </Link>efficient solutions in process industries, there has been an increasing adoption of inverters to monitor motor speeds and all electrical equipment that leads to reduced energy consumption and improved efficiency. The use of inverters enables industry to cut its carbon footprint substantially, and thus contribute towards a greener future.</p>
                  </Tab>
                  <Tab eventKey="toc" title="Table of Content">
                    <p>Table of Content</p>
                  </Tab>
                  <Tab eventKey="methodology" title="Request Methodology">
                    <p>Request Methodology</p>
                  </Tab>
                  <Tab eventKey="customization" title="Request Customization">
                    <p>Request Customization</p>
                  </Tab>
                </Tabs>
                </main>
              </div>
            </div>
          </div>
        </div>
      </div>
  )
}

export default Report